2023-12-02 15:42:33 - 'C:\Users\markn\OneDrive\Xanantec Work\SIA\ImageAnalysisSIA\tests\test_SupportUtil.py' - 001 - Test error message
